package models

import "time"

// IntentPlan stores a pending network change plan generated by the Intent Engine.
// Plans expire 10 minutes after creation if not applied.
type IntentPlan struct {
	ID          string    `gorm:"primaryKey;type:varchar(36);not null" json:"id"`
	WorkspaceID string    `gorm:"size:36;index"                        json:"workspaceId"`
	Namespace   string    `gorm:"size:200"                             json:"namespace"`
	Intent      string    `gorm:"type:text"                            json:"intent"`      // original natural-language request
	Summary     string    `gorm:"type:text"                            json:"summary"`     // human-readable Markdown diff
	ChangesJSON string    `gorm:"type:text"                            json:"changesJson"` // JSON array of CRDChange
	RiskLevel   string    `gorm:"size:20"                              json:"riskLevel"`   // low | medium | high
	CreatedAt   time.Time `                                             json:"createdAt"`
	ExpiresAt   time.Time `gorm:"index"                                json:"expiresAt"`
}

func (IntentPlan) TableName() string { return "t_intent_plan" }
