apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lattice.fullname" . }}-license
  labels:
    {{- include "lattice.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.license.enabled }}
  license.jwt: {{ .Values.license.fileContents | b64enc | quote }}
  {{- else }}
  {}
  {{- end }}
