apiVersion: v1
kind: Service
metadata:
  name: {{ include "lattice.fullname" . }}
  labels:
    {{- include "lattice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
      {{- if .Values.service.apiNodePort }}
      nodePort: {{ .Values.service.apiNodePort }}
      {{- end }}
    - name: nats
      port: {{ .Values.service.natsPort }}
      targetPort: nats
      protocol: TCP
      {{- if .Values.service.natsNodePort }}
      nodePort: {{ .Values.service.natsNodePort }}
      {{- end }}
  selector:
    {{- include "lattice.selectorLabels" . | nindent 4 }}
